# vim: set ft=zsh:

# if not an interactive shell, return
[[ ! -o interactive ]] && return

#zmodload zsh/zprof
#zprof -c


# detect os
case "$OSTYPE" in
  darwin*)
    OS=darwin
  ;;
  linux*)
    OS=linux
  ;;
  freebsd*)
    OS=freebsd
  ;;
  dragonfly*|netbsd*|openbsd*)
    # ...
  ;;
esac
export OS


# detecth ssh
IS_SSH="${IS_SSH:-0}"
if [[ -n "$SSH_CLIENT" || -n "$SSH_TTY" ]]; then
    IS_SSH=1
fi
export IS_SSH


## load local env vars if they exist
[ -s $HOME/.zshrc_pre ] && . $HOME/.zshrc_pre

## invoke main custom config entrypoint
source $HOME/.zshrc.d/load.zsh
#zprof
